version: '3.1'

services:
  iot-frontend:
    build: ../iot-frontend
    container_name: iot-frontend
    ports:
      - '80:3000'
    volumes:
      - ./../iot-frontend:/home/app/iot-frontend
  
  iot-api:
    image: prodalia/iot-api:latest
    container_name: iot-api
    environment:
      - API_URL=http://localhost:4000/
    ports:
      - '4000:4000'
    volumes:
      - ./../iot-api:/home/app/iot-api
      - img:/img
    networks:
      - iot-net
  iot-db:
    image: prodalia/iot-db:latest
    container_name: iot-db
    volumes:
      - database:/data/db
    networks:
      - iot-net

networks:
  iot-net:

volumes:
  img:
  database:
